version: '3.8'
services:
  fe-app:
    image: crpi-0822sqe9pdavunw3.cn-hangzhou.personal.cr.aliyuncs.com/yanghao_node/yang:0.1
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/hao.yang/Desktop/test/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: yang
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/hao.yang/code:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge

